spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/micro-service?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Jason
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  transaction:
    rollback-on-commit-failure: true
mybatis:
  type-aliases-package: com.jason.product.model
  mapper-locations: classpath:/mapper/*-mapper.xml
eureka:
  client:
    service-url:
      defaultZone: http://server2:9998/eureka
server:
  port: 3333
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error
