spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    password: Jason
    username: root
    url: jdbc:mysql://localhost:3306/micro-service?useSSL=false&serverTimezone=GMT%2B8
eureka:
  client:
    service-url:
      defaultZone: http://server2:9998/eureka, http://server3:9999/eureka
server:
  port: 4440
mybatis:
  mapper-locations: classpath:/mapper/*-mapper.xml
  type-aliases-package: com.jason.order.model
